version: '3'

services:
    tws:
        image: mgvazquez/ibgateway:latest
        restart: unless-stopped
        ports:
            - 5900:5900
        environment:
            - TWSUSERID=IBKRID
            - TWSPASSWORD=PASSWORD
            - TRADING_MODE=live
            - VNC_PASSWORD=hello123
            - VNC_PORT=5900
    api:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - 5000:5000
        depends_on: 
            - tws
